#!/usr/bin/env bash
# template-probe.sh — Custom-template probe for issue #73 (promoted v0.1.0, 2 uses ≥ bar: prototype + smoke PASS).
# Model: enrichment-probe.sh T-structure with template_check per arm.
# Offline-safe: never passes --strict; committed npm fixture + committed
#   Fixtures/templates/*.scriban files only, temp files for error arms.
#   T1 header/footer/loop render: committed header-footer-loop.scriban on npm
#      fixture (substituted total, per-license name/version/spdx, Generated by
#      olaf toolVersion + generatedAt non-empty) + groups.scriban (group
#      headers + nested items) + holder-passthrough shape ({{copyright}}
#      renders, carries a known name, no leftover tag).
#   T2 missing-file -> 2 + "Template not found" stderr.
#   T3 syntax-error -> 2 + "line N" stderr.
#   T4 unknown-field renders empty, exit 0, no crash.
#   R1 matrix regression: json/yaml/xml/html `direct` markers untouched
#      (defaults stay hand-coded C#, plan DECISION 3 binding).
# Rules: repo-relative, idempotent (mktemp cleaned), no secrets, exit 0/1/2.
VERSION="0.1.0"
set -euo pipefail

# ---- Canonical root resolution (factory depth: ../../.. per parser-coverage-probe.sh) ----
ROOT=""
if git rev-parse --show-toplevel >/dev/null 2>&1; then
  ROOT="$(git rev-parse --show-toplevel)"
else
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -f "$SCRIPT_DIR/../../../olaf.slnx" ]]; then
    ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
  else
    echo "Cannot locate repo root (no git top-level, no olaf.slnx fallback)." >&2
    exit 2
  fi
fi

# ---- Canonical pass/fail ----
fail=0
pass() { echo "PASS: $*"; }
fail_msg() { echo "FAIL: $*"; fail=1; }

# ---- Canonical temp-dir with KEEP_TEMP ----
WORKDIR=""
KEEP_TEMP=0
TIMEOUT_SECS=60
PROJECT_REL="src/Olaf.Cli"
FIXTURE_REL="tests/Olaf.Tests/Fixtures/npm"
TPLDIR_REL="tests/Olaf.Tests/Fixtures/templates"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--timeout <secs>] [--workdir <dir>] [--keep-temp] [--help] [--version]

Custom-template probe (issue #73): header/footer/loop render (T1),
missing-file->2 (T2), syntax-error->2 + line N (T3), unknown-field
renders empty exit 0 (T4), format-matrix regression (R1). Offline-safe:
committed npm fixture + committed template fixtures only.

Options:
  --timeout <n>   per-scan timeout in seconds (default: 60)
  --workdir <dir> work dir (default: mktemp -d under \${TMPDIR:-/tmp})
  --keep-temp     keep temp work dir for debugging (default: remove)
  --help          show this help and exit 0
  --version       print VERSION and exit 0

Exit codes: 0 all PASS, 1 assertion failure, 2 usage/environment error.

Examples:
  $(basename "$0")
  $(basename "$0") --timeout 30 --keep-temp
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help) usage; exit 0 ;;
    --version) echo "$(basename "$0") $VERSION"; exit 0 ;;
    --timeout) TIMEOUT_SECS="${2:-}"; shift 2 ;;
    --timeout=*) TIMEOUT_SECS="${1#*=}"; shift ;;
    --workdir) WORKDIR="${2:-}"; shift 2 ;;
    --workdir=*) WORKDIR="${1#*=}"; shift ;;
    --keep-temp) KEEP_TEMP=1; shift ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if ! [[ "$TIMEOUT_SECS" =~ ^[0-9]+$ ]]; then
  echo "Invalid --timeout '$TIMEOUT_SECS': must be a positive integer." >&2
  exit 2
fi

PROJECT="$ROOT/$PROJECT_REL"
FIXTURE="$ROOT/$FIXTURE_REL"
TPLDIR="$ROOT/$TPLDIR_REL"
[[ -d "$PROJECT" ]] || { echo "CLI project not found: $PROJECT" >&2; exit 2; }
[[ -d "$FIXTURE" ]] || { echo "Fixture not found: $FIXTURE" >&2; exit 2; }
[[ -d "$TPLDIR" ]] || { echo "Template fixture dir not found: $TPLDIR" >&2; exit 2; }
[[ -f "$ROOT/olaf.slnx" ]] || { echo "Repo root has no olaf.slnx: $ROOT" >&2; exit 2; }
for cmd in dotnet timeout; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "Missing required command: $cmd" >&2; exit 2; }
done

if [[ -z "$WORKDIR" ]]; then
  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/template-probe-XXXXXX")"
  MADE_TMP=1
else
  mkdir -p "$WORKDIR"
  MADE_TMP=0
fi
cleanup() {
  if (( ! KEEP_TEMP )) && (( MADE_TMP )) && [[ -d "$WORKDIR" ]]; then
    rm -rf "$WORKDIR"
  fi
}
trap cleanup EXIT

RC=0
run_scan() {
  # run_scan <tag> <inputdir> <format> [extra args...]; stdout-><tag>.stdout
  local tag="$1" input="$2" fmt="$3"; shift 3
  set +e
  timeout "${TIMEOUT_SECS}s" dotnet run --project "$PROJECT" --no-launch-profile -- --input "$input" --format "$fmt" "$@" >"$WORKDIR/$tag.stdout" 2>"$WORKDIR/$tag.stderr"
  RC=$?
  set -e
  if [[ "$RC" -eq 124 ]]; then
    fail_msg "$tag timed out after ${TIMEOUT_SECS}s"
  fi
}

run_template() {
  # run_template <tag> <inputdir> <template-path> [extra args...]; stdout-><tag>.stdout
  local tag="$1" input="$2" tpl="$3"; shift 3
  set +e
  timeout "${TIMEOUT_SECS}s" dotnet run --project "$PROJECT" --no-launch-profile -- --input "$input" --template "$tpl" "$@" >"$WORKDIR/$tag.stdout" 2>"$WORKDIR/$tag.stderr"
  RC=$?
  set -e
  if [[ "$RC" -eq 124 ]]; then
    fail_msg "$tag timed out after ${TIMEOUT_SECS}s"
  fi
}

echo "== template-probe v$VERSION =="
echo "repo: $ROOT"
echo "work: $WORKDIR"

echo "-- step 0: build CLI --"
if ! dotnet build "$PROJECT" --nologo -v minimal; then
  echo "FAIL: dotnet build failed." >&2
  exit 1
fi
pass "build: dotnet build OK"

echo "-- T1: header/footer/loop render on npm fixture + committed templates --"
run_template "t1-loop" "$FIXTURE" "$TPLDIR/header-footer-loop.scriban"
[[ "$RC" -eq 0 ]] && pass "T1 loop exit 0" || fail_msg "T1 loop exit $RC (want 0)"
if [[ -s "$WORKDIR/t1-loop.stdout" ]]; then
  if grep -q "{{" "$WORKDIR/t1-loop.stdout"; then
    fail_msg "T1 loop: unsubstituted {{ tag left in output"
  else
    pass "T1 loop: no unsubstituted {{ tags"
  fi
  if grep -q "Third-Party Attribution" "$WORKDIR/t1-loop.stdout"; then
    pass "T1 loop: custom header present"
  else
    fail_msg "T1 loop: custom header missing"
  fi
  if grep -qE "Total: [0-9]+, Resolved: [0-9]+, Unknown: [0-9]+" "$WORKDIR/t1-loop.stdout"; then
    pass "T1 loop: substituted total line ($(grep -oE 'Total: [0-9]+, Resolved: [0-9]+, Unknown: [0-9]+' "$WORKDIR/t1-loop.stdout" | head -n 1))"
  else
    fail_msg "T1 loop: total line not substituted"
  fi
  for pin in "express@" "debug@" "SPDX: MIT"; do
    if grep -qF -- "$pin" "$WORKDIR/t1-loop.stdout"; then
      pass "T1 loop: per-license pin '$pin'"
    else
      fail_msg "T1 loop: per-license pin '$pin' missing"
    fi
  done
  if grep -qE "Generated by olaf .+ at .+" "$WORKDIR/t1-loop.stdout"; then
    pass "T1 loop: footer toolVersion + generatedAt non-empty"
  else
    fail_msg "T1 loop: footer toolVersion/generatedAt missing or empty"
  fi
else
  fail_msg "T1 loop: empty stdout"
fi

run_template "t1-groups" "$FIXTURE" "$TPLDIR/groups.scriban"
[[ "$RC" -eq 0 ]] && pass "T1 groups exit 0" || fail_msg "T1 groups exit $RC (want 0)"
if grep -q "## MIT (2)" "$WORKDIR/t1-groups.stdout" 2>/dev/null; then
  pass "T1 groups: MIT group header with count"
else
  fail_msg "T1 groups: '## MIT (2)' header missing"
fi
if grep -qF -- "- express@" "$WORKDIR/t1-groups.stdout" 2>/dev/null; then
  pass "T1 groups: nested item '- express@'"
else
  fail_msg "T1 groups: nested item '- express@' missing"
fi

printf '{{#each licenses}}{{name}}|{{copyright}};\n{{/each}}' > "$WORKDIR/holder.scriban"
run_template "t1-holder" "$FIXTURE" "$WORKDIR/holder.scriban"
[[ "$RC" -eq 0 ]] && pass "T1 holder exit 0" || fail_msg "T1 holder exit $RC (want 0)"
if grep -q "{{" "$WORKDIR/t1-holder.stdout" 2>/dev/null; then
  fail_msg "T1 holder: unsubstituted {{ tag left in output"
else
  pass "T1 holder: no unsubstituted {{ tags (holder passthrough shape)"
fi
if grep -qF -- "express|" "$WORKDIR/t1-holder.stdout" 2>/dev/null; then
  pass "T1 holder: known package name passes through"
else
  fail_msg "T1 holder: known package name 'express|' missing"
fi

echo "-- T2: missing template file -> 2 --"
run_template "t2-missing" "$FIXTURE" "$TPLDIR/does-not-exist.scriban"
[[ "$RC" -eq 2 ]] && pass "T2 missing exit 2" || fail_msg "T2 missing exit $RC (want 2)"
if grep -q "Template not found" "$WORKDIR/t2-missing.stderr" 2>/dev/null; then
  pass "T2 missing: stderr carries 'Template not found'"
else
  fail_msg "T2 missing: stderr lacks 'Template not found'"
fi

echo "-- T3: syntax error -> 2 + line N --"
printf 'header\n{{#each licenses}}\nno-close\n' > "$WORKDIR/bad.scriban"
run_template "t3-badsyntax" "$FIXTURE" "$WORKDIR/bad.scriban"
[[ "$RC" -eq 2 ]] && pass "T3 bad-syntax exit 2" || fail_msg "T3 bad-syntax exit $RC (want 2)"
if grep -qE "line [0-9]+" "$WORKDIR/t3-badsyntax.stderr" 2>/dev/null; then
  pass "T3 bad-syntax: stderr carries line number ($(grep -oE 'line [0-9]+' "$WORKDIR/t3-badsyntax.stderr" | head -n 1))"
else
  fail_msg "T3 bad-syntax: stderr lacks 'line N'"
fi

echo "-- T4: unknown field renders empty, exit 0, no crash --"
printf 'A-{{nosuchfield}}-B' > "$WORKDIR/unk.scriban"
run_template "t4-unknown" "$FIXTURE" "$WORKDIR/unk.scriban"
[[ "$RC" -eq 0 ]] && pass "T4 unknown exit 0" || fail_msg "T4 unknown exit $RC (want 0)"
if [[ "$(cat "$WORKDIR/t4-unknown.stdout" 2>/dev/null)" == "A--B" ]]; then
  pass "T4 unknown: renders 'A--B' (empty, no crash)"
else
  fail_msg "T4 unknown: want 'A--B', got '$(cat "$WORKDIR/t4-unknown.stdout" 2>/dev/null | head -c 80)'"
fi

# ---- Canonical R1 format-matrix regression (from _template.sh 0.2.3) ----
r1_matrix_regression() {
  # r1_matrix_regression [formats...]; default: json yaml xml html.
  local formats=("$@")
  (( ${#formats[@]} )) || formats=(json yaml xml html)
  local R1FAIL=0 f pat
  echo "-- R1 format-matrix regression --"
  for f in "${formats[@]}"; do
    run_scan "r1-$f" "$FIXTURE" "$f"
    if [[ "$RC" -ne 0 ]]; then
      fail_msg "R1/$f scan exited $RC"; R1FAIL=1; continue
    fi
    case "$f" in
      json) pat='"direct"' ;;
      yaml) pat='direct:' ;;
      xml) pat='<direct>' ;;
      html) pat='<th>Direct</th>' ;;
      *) fail_msg "R1/$f: no marker for format"; R1FAIL=1; continue ;;
    esac
    if grep -qF -- "$pat" "$WORKDIR/r1-$f.stdout"; then
      pass "R1/$f carries $pat"
    else
      fail_msg "R1/$f missing $pat"; R1FAIL=1
    fi
  done
  if (( ! R1FAIL )); then pass "R1 MATRIX OK: ${formats[*]} untouched"; fi
}

# ---- R1 format-matrix regression: json/yaml/xml/html direct markers untouched ----
r1_matrix_regression

echo "== summary =="
if [[ "$fail" -eq 0 ]]; then
  echo "TEMPLATE-PROBE OK: T1-T4 + R1 all pass."
  exit 0
else
  echo "TEMPLATE-PROBE FAILED: see FAIL lines above." >&2
  exit 1
fi
